### ISSUE TITLE
TypeError: Cannot read property 'escapedName' of undefined

### ISSUE THREAD

**Issue by ravisharnagat** [juusaw/ts-to-io#29]
Getting following error:
`Error: Failed to generate a codec for:`

Getting this is stack trace:
```
TypeError: Cannot read property 'escapedName' of undefined
    at Object.isArrayType (/Users/ravisharnagat/ts-2-iots/types.js:50:24)
    at /Users/ravisharnagat/ts-2-iots/index.js:90:22
    at /Users/ravisharnagat/ts-2-iots/index.js:33:48
    at Array.map (<anonymous>)
    at /Users/ravisharnagat/ts-2-iots/index.js:52:14
    at /Users/ravisharnagat/ts-2-iots/index.js:107:42
    at handleDeclaration (/Users/ravisharnagat/ts-2-iots/index.js:128:69)
    at /Users/ravisharnagat/ts-2-iots/index.js:139:21
    at visitNodes (/Users/ravisharnagat/ts-2-iots/node_modules/typescript/lib/typescript.js:18973:30)
    at Object.forEachChild (/Users/ravisharnagat/ts-2-iots/node_modules/typescript/lib/typescript.js:19206:24)
```

**Comment by ravisharnagat** [comment]
We are getting the error in following part of the code:
```js
export function isArrayType(type: ts.Type) {
  return type.symbol.escapedName === 'Array'
}
```

Adding `type.symbol &&` check will fix the issue.

**Fix:**
```js
export function isArrayType(type: ts.Type) {
  return type.symbol && type.symbol.escapedName === 'Array'
}
```

**Comment by ravisharnagat** [comment]
#30 fixes this
